[project]
name = "chip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "groq",
    "httpx",
    "uvicorn",
    "openai",
    "orjson",
    "pydantic-ai-slim[mcp]",
    "pydantic-settings",
    "python-dotenv",
    "logfire",
    "temporalio",
    "twilio",
    "supabase",
    "tiktoken",
    "opentelemetry-instrumentation-fastapi>=0.57b0",
    "opentelemetry-instrumentation-httpx>=0.57b0",
    "opentelemetry-instrumentation-requests>=0.57b0",
    "opentelemetry-instrumentation-sqlite3>=0.57b0",
    "opentelemetry-instrumentation-urllib>=0.57b0",
]

[dependency-groups]
dev = [
    "debugpy",
    "pytest",
    "respx",
    "ruff",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
python_files = [
    "test_*.py",
]
